### ISSUE TITLE
Composer PSR-4 autoload issue

### ISSUE THREAD

**Issue by pugsley** [Mastercard/oauth1-signer-php#1]
I was having an issue where the Mastercard classes weren't being found when composer is run without optimise `-o`. I'm fairly sure it's because there's an unnecessary `Mastercard` directory in the source tree: vendor/mastercard/oauth1-signer/src/**Mastercard**/Developer

The PSR-4 autoload spec in composer (https://getcomposer.org/doc/04-schema.md#psr-4) states that:
> Note that as opposed to the older PSR-0 style, the prefix (Foo\\) is not present in the file path.

This works with `--optimize`/`-o` because composer does a directory search and includes all found classes.

All that's required to fix is to move the `Developer` directory down a level and remove the `Mastercard` directory. e.g. from `vendor/mastercard/oauth1-signer/src/Mastercard/Developer` > `vendor/mastercard/oauth1-signer/src/Developer`

Thanks!

**Comment by jaaufauvre** [comment]
Thanks @pugsley! I just created a PR addressing that issue.

**Comment by pugsley** [comment]
Nice one, thanks for the fast turn-around!
