### ISSUE TITLE
ReasonCode":"INVALID_AUTH_HEADER"  "Description":"Bad Request - No Authorization

### ISSUE THREAD

**Issue by masudmiah000** [Mastercard/oauth1-signer-php#9]
```
"headers": [
    "Content-Type: application/json",
    "Content-Length: 253",
    "Authorization : OAuth oauth_consumer_key="qvh9jTJxTr1ctI3I8SErGhKyFyVpyhM0stkfc0867b667469%2165f16e2174cb442f9bfbf11de13bf3860000000000000000",oauth_nonce="oWom9rr820qKGwUk",oauth_timestamp="1642489189",oauth_signature_method="RSA-SHA256",oauth_version="1.0",oauth_body_hash="ZY7uqZIAM0c1hZnyFxurm8P%2F56tZK%2Bo6g2DhUw5Syp8%3D",oauth_signature="djs9ouQY3AE4g5xyzaZ%2B2T6eLJCt7FXxCikIsAd9Ks8fxK19EJ2oKz0HfnDjeDckjznJGUQUA%2FzFzOTBcXv3KiqsBPGwdPmT6ug8dYIStrFL1R7PVo19%2FgiRFEnxU3DLG1TJvG4IwHRhnnldUKFVhOvZgHB4NmjbLY0VbpUdD2qR1RuHSHTrUF8KBaWA28j3re9bOqD8uspujOTdhqddstdIBez%2B%2FnXLR0Lx06oTZiM38z97f9QCqo2%2Fj4sOEh%2FHkm44b%2BLXlQeFsW%2BiXP3t5O7mPda9vpT3hK6%2BM5%2F56et1rMPQHHvzZpnB2JHvH1AkSVV64OMLBytYz3YS%2Brk6vw%3D%3D""
]
```

`Request URL : https://sandbox.api.mastercard.com/send/v1/partners/XXXXXXXXXXXX/transfers/payment`

`"body":"{"payment_transfer":{"payment_origination_country":"XXX","funding_transaction_reference":{"network":"XXXX","reference_number":"XXXXXXX"},"transfer_priority":"XXX"}}"`

I am doing a guzzle post call with JSON post body, from PHP | Laravel project

**Comment by TutteRamson** [comment]
1. Does any of your other calls to the same service(Mastercard Send) succeed?
2. Do you get the error from your PHP client or from Mastercard Gateway that validates the request? Here are the [error codes returned from the Gateway](https://developer.mastercard.com/platform/documentation/security-and-authentication/gateway-error-codes/).
3. Could you please share your code that shows how you build and sign the request, in case some steps are missed out there?

p.s.(FYI): Unless it is a feature request in the library or a bug fix, the expectation is that developers reach out to Mastercard Technical Support available here: https://developer.mastercard.com/support 
Based on the details you provide(for the questions asked above) we will decide whether to guide you to the support team or not. Thanks.

**Comment by masudmiah000** [comment]
> 

Thanks for your reply.

I am receiving this error from Mastercard end.

```
{
  "Errors": {
    "Error": [
      {
        "Source": "Gateway",
        "ReasonCode": "INVALID_AUTH_HEADER",
        "Description": "Bad Request - No Authorization header set.",
        "Recoverable": false,
        "Details": null
      }
    ]
  }
}
```
this is the response I received from Mastercard end.

in above comment shared my request bodies. I am doing a http call via Guzzle

**Comment by jaaufauvre** [comment]
Check you properly set and send the `Authorization` header. With Guzzle, `headers` must be an associative array aka a map.

See: https://docs.guzzlephp.org/en/stable/request-options.html#headers

Or the code samples in the README here: https://github.com/Mastercard/oauth1-signer-php#guzzlehttp-
